Repository pulumi/pulumi-gcp, pull requests merged in 2019-06, with the labels that each got.

#166 CHANGELOG: Adding a link to the GCP setup documentation
  README.md
Labels: area/docs, impact/no-changelog-required

#168 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
Labels: area/providers

#169 Upgrade to v2.9.1 of the Google Beta Terraform Provider
  CHANGELOG.md
  go.mod
  go.sum
Labels: area/providers, kind/enhancement
